version: '1.0'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trello
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trello
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres-data: